### ISSUE TITLE
Error with loading dataset

### ISSUE THREAD

**Issue by nirmal2k** [luyug/COIL#15]
The error I get while running run_msmarco.py

Target schema's field names are not matching the table's field names: ['qry', 'pos', 'neg'], ['neg', 'pos', 'qry']

I have downloaded the psg-train and extracted them. THe path_to_tsv variable in GroupedMarcoTrainDataset has all the .json files,

**Comment by luyug** [comment]
Please confirm that you are using the specified version `datasets`.

**Comment by nirmal2k** [comment]
Thanks, using the specified _datasets_ version worked!
