### ISSUE TITLE
Padding Tokens - in the inverted list index

### ISSUE THREAD

**Issue by GeorgeSanchezTR** [luyug/COIL#17]
do_encode - will pad the passages to maximum passage length 
reps will now include the representation for the padding token - which will then be added to the index
the padding token in the index affects the score because any query containing any padding will now match that token 

Should the padding token 0 be removed from the index after sharding or during the sharding process?

**Comment by luyug** [comment]
Pad tokens are not included in the index. https://github.com/luyug/COIL/blob/6d15679f9ddb8f29c814d19e674333511c45feb3/run_marco.py#L253-L262

**Comment by GeorgeSanchezTR** [comment]
This block of code addresses [CLS] and [SEP] but not [PAD]

**Comment by GeorgeSanchezTR** [comment]
Ok looking at this. [PAD] tokens are not explicitly handled but are excluded by a series of steps - that if you do not follow the steps in order the tokens will end up in the index. First - a single tokenizing process can not be used for both index and model training.

For the index: the following steps need to happen
1. Call tokenizer.encode with the text w/o padding and special tokens - write the input ids to a file
2. During model.encode - read the output of step 1 call tokenizer.encode_plus with padding w/o special tokens then call model.encode
3. Only the the token ids in step 1 are added to the index.

In order for the forward method to have the same score as the retrieval scoring
1. Call use tokenizer.encode_plus with padding w/o special tokens then call model(qry_input=qry_input, doc_input=doc_input)
2. The attention mask would determine which tokens are included in the score, [CLS] is handled in the model code but [SEP] is not.
Thanks!
