### ISSUE TITLE
Small typo and bug?

### ISSUE THREAD

**Issue by MXueguang** [luyug/COIL#2]
Hi @luyug, Great work!!!!

I am trying to replicate COIL, there is some typo I noticed.
1. in README.md Encoding section
```
    --token_dim 768 \  
    --cls_dim 32 \ 
```
should be 32, 768 instead?

2. https://github.com/luyug/COIL/blob/813a076ad7526536dad5d4fc71eee5f7f8113700/trainer.py#L42
`num_training_steps` should be passed into the function rather than `warmup_steps`?

**Comment by luyug** [comment]
Thanks for catching these! Will push a fix asap.

I am super surprised that the second typo happened during the refactor. It actually got me worried and I went back to check all of my other repos that have the same function call. Fortunately they all seem correct.. I guess it is just a bad idea to multi-task on too many things at the same time..

**Comment by MXueguang** [comment]
closing the issue, since (2) get fixed
